export const WEAPONS = {
  pistol: {
    id: 'pistol',
    name: 'Starter Pistol',
    price: 0,
    damage: 10,
    fireDelay: 0.35,
    ammo: Infinity,
    speed: 720,
    pellets: 1,
    spread: 0,
    color: '#ffd166',
    description: 'Unlimited ammo, steady and reliable.',
  },
  smg: {
    id: 'smg',
    name: 'SMG',
    price: 150,
    damage: 7,
    fireDelay: 0.1,
    ammo: 120,
    speed: 760,
    pellets: 1,
    spread: 0,
    color: '#9ee7ff',
    description: 'Fast fire rate, lower damage.',
  },
  shotgun: {
    id: 'shotgun',
    name: 'Shotgun',
    price: 250,
    damage: 8,
    fireDelay: 0.7,
    ammo: 30,
    speed: 660,
    pellets: 5,
    spread: 0.44,
    color: '#ffb86c',
    description: 'Five-pellet spread, best up close.',
  },
  rifle: {
    id: 'rifle',
    name: 'Rifle',
    price: 300,
    damage: 25,
    fireDelay: 0.45,
    ammo: 40,
    speed: 860,
    pellets: 1,
    spread: 0,
    color: '#d7eef7',
    description: 'Accurate, high damage shots.',
  },
  plasma: {
    id: 'plasma',
    name: 'Plasma Gun',
    price: 500,
    damage: 40,
    fireDelay: 0.5,
    ammo: 25,
    speed: 700,
    pellets: 1,
    spread: 0,
    radius: 8,
    color: '#b38cff',
    description: 'Powerful glowing shots.',
  },
  rocket: {
    id: 'rocket',
    name: 'Rocket Launcher',
    price: 700,
    damage: 80,
    fireDelay: 1.2,
    ammo: 8,
    speed: 520,
    pellets: 1,
    spread: 0,
    radius: 9,
    area: 90,
    color: '#ef476f',
    description: 'Slow arcade blast with area damage.',
  },
};

export const WEAPON_LIST = Object.values(WEAPONS);

export function getWeapon(id = 'pistol') {
  return WEAPONS[id] || WEAPONS.pistol;
}

