export const ZOMBIE_TYPES = {
  normal: {
    id: 'normal',
    label: 'Normal',
    health: 30,
    speed: 1,
    damage: 10,
    reward: 10,
    money: 5,
    radius: 16,
    color: '#78a85d',
    kind: 'zombie',
  },
  fast: {
    id: 'fast',
    label: 'Fast',
    health: 18,
    speed: 1.8,
    damage: 7,
    reward: 15,
    money: 8,
    radius: 14,
    color: '#9be564',
    kind: 'zombie',
  },
  tank: {
    id: 'tank',
    label: 'Tank',
    health: 120,
    speed: 0.55,
    damage: 20,
    reward: 30,
    money: 15,
    radius: 23,
    color: '#6b8f4e',
    kind: 'zombie',
  },
  spitter: {
    id: 'spitter',
    label: 'Spitter',
    health: 45,
    speed: 0.8,
    damage: 8,
    reward: 20,
    money: 10,
    radius: 17,
    color: '#57b8ff',
    kind: 'rival',
  },
  exploder: {
    id: 'exploder',
    label: 'Boomer',
    health: 35,
    speed: 1.1,
    damage: 25,
    reward: 25,
    money: 12,
    radius: 18,
    color: '#ff8c42',
    kind: 'zombie',
  },
  boss: {
    id: 'boss',
    label: 'Boss',
    health: 500,
    speed: 0.45,
    damage: 25,
    reward: 100,
    money: 60,
    radius: 31,
    color: '#b38cff',
    kind: 'rival',
  },
};

export function getZombieType(id = 'normal') {
  return ZOMBIE_TYPES[id] || ZOMBIE_TYPES.normal;
}
